### ISSUE TITLE
Backend API: need API to deal with transport storage from backend side

### ISSUE THREAD

**Issue by vitalyster** [hanzz/spectrum2#59]
Backends didn't have access to transport storage and need to reinvent it (as transwhat backend)

**Comment by piwats** [comment]
+1

**Comment by moyamo** [comment]
Do you propose a generic access to the backend database (i.e. can execute any query) or just access to existing spectrum tables?

**Comment by moyamo** [comment]
I don't think much changes are needed in spectrum for transwhat to work without a database. If after a user logs in something similar to a handleBuddyChangedPayload (with all the Buddy fields filled in) is sent transwhat should be able to get rid of the MySQL database.

**Comment by moyamo** [comment]
I still want to know what you have in mind. Will the Backend API allow plugins to create and manipulate tables or will it just allow you to query existing tables?

The problem is that just querying and modifying existing tables is not very useful. Spectrum already allows this through buddyChanged, updateBuddy and the like. If you allow the plugin to execute arbitrary SQL queries then the plugin has to worry about compatibility between the different databases. In this case the plugin might as well use the databases directly. If spectrum provides a high-level interface to the database then the type of queries the plugin can make will be limited.

So what will it be?

**Comment by hanzz** [comment]
I've done the first part in commit ef1711db20b26565a33b8a7dfae10b6e8f6cb600.

The backend can send following new option in backend config:
```
[features]
send_buddies_on_login = 1
```

And after that, Spectrum will send TYPE_BUDDIES protobuf message after the TYPE_LOGIN message including all the buddies from database.

**Comment by vitalyster** [comment]
Transwhat support is done in 2.0
